apiVersion: mssql.f-wi.com/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: mssql-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mssql-operator
  name: cluster-sample
spec:
  # TODO(user): Add fields here
