apiVersion: mssql.f-wi.com/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: database-sample
    app.kubernetes.io/part-of: mssql-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mssql-operator
  name: database-sample
spec:
  name: testdb1
  clusterName: cluster-sample
